PUT http://localhost:3003/api/blogs/64b518c54782f34af8fac3ca
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0YWZkY2Y0MTRmMDhkOGI0MDg5MjA4ZSIsImlhdCI6MTY4OTUwMTg2MH0.PRSwpncsWf0VTpAzKu-Zy_GycUR2iL1piVkAHbtWnd8

{
    "title": "Title One",
    "author": "Author One",
    "url": "www.urlone.com",
    "likes": 5,
    "user": "64afdcf414f08d8b4089208e"
}